services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${FRONTEND_PORT:-3000}:3000

networks:
  default:
    name: axanetwork
    external: true

